Drop Node event when EC2 instance does not exist
kubernetes/cloud-provider-aws pull request #753
Opened 2023-11-27 21:17 UTC by cartermckinnon

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This avoids unnecessary retries for invalid Node events (the corresponding EC2 instance does not exist). When many Nodes are created and deleted, the event queue of the tagging controller can grow, causing delays in handling valid events.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2023-11-27 22:54 UTC, cartermckinnon commented
Something seems wonky with the CI, I'll look into it.

2023-11-27 23:06 UTC, cartermckinnon commented
/retest

All failures are related to persistent volumes, doesn't seem related to this change.

2023-11-28 01:30 UTC, tzneal reviewed
It look ok to me, but can we add a test for this new behavior in tagging_controller_test.go?

2023-11-30 00:09 UTC, cartermckinnon commented
/retest

2023-11-30 02:00 UTC, cartermckinnon commented
The CI is definitely hosed, same cases have been red in k/k since ~11/24: https://testgrid.k8s.io/presubmits-ec2#pull-kubernetes-e2e-ec2

2023-11-30 05:20 UTC, cartermckinnon commented
@tzneal added a couple unit test cases 👍

2023-11-30 19:45 UTC, cartermckinnon commented
Haven't had a chance to go down the rabbit hole. Looks like things broke when the `kubekins` image was bumped in the test spec, I assume a change in cloud-provider-aws-test-infra is the issue but I don't see anything obvious in the commit log.

@dims do you have a guess?

2023-11-30 21:58 UTC, cartermckinnon commented
@dims I'll try to get a fix up 👍

2023-12-01 17:23 UTC, cartermckinnon commented
/retest

2023-12-01 18:43 UTC, mmerkes approved these changes
LGTM

2023-12-01 18:54 UTC, ndbaker1 requested changes
Thanks for picking this up! did we also want to make the queue size visible with some logging around [here](https://github.com/kubernetes/cloud-provider-aws/blob/11088788f267d02cf32ad177467312a11c5692ec/pkg/controllers/tagging/tagging_controller.go#L205)? (since dequeuing latency isn't the most direct metric)

2023-12-01 19:24 UTC, cartermckinnon commented
> did we also want to make the queue size visible

I plan to add a metric for this in a separate PR, because it'd be helpful to debug in the future; but I think dequeue latency is still the more important metric to track and alarm on. There can be many events in the queue that are no-ops, and that doesn't necessarily have an impact e.g. how quickly a new Node is tagged.

2023-12-01 19:33 UTC, ndbaker1 approved these changes

2023-12-01 21:04 UTC, dims commented
/approve
/lgtm

2023-12-01 21:09 UTC, merged